### Bibliotecas Correlatas            
import pandas as pd
import numpy as np

### Encaminhamento ao Diretório "DADOS" e "IMAGENS"
caminho_dados = "/home/sifapsc/scripts/matheus/dados_dengue/"
caminho_imagens = "/home/sifapsc/scripts/matheus/resultado_imagens/"
caminho_correlacao = "/home/sifapsc/scripts/matheus/resultado_correlacao/"

### Renomeação variáveis pelos arquivos
casos = "serie_casos_sc.csv"
focos = "serie_focosdia_sc.csv"
merge = "merge.csv"
tmax = "samet_tmax.csv"
tmed = "samet_tmed.csv"
tmin = "samet_tmin.csv"

### Abrindo Arquivos
casos = pd.read_csv(f"{caminho_dados}{casos}", low_memory = False)
focos = pd.read_csv(f"{caminho_dados}{focos}", low_memory = False)
merge = pd.read_csv(f"{caminho_dados}{merge}", low_memory = False)
tmax = pd.read_csv(f"{caminho_dados}{tmax}", low_memory = False)
tmed = pd.read_csv(f"{caminho_dados}{tmed}", low_memory = False)
tmin = pd.read_csv(f"{caminho_dados}{tmin}", low_memory = False)

### Dicionários para Troca de Nomes
lista = {"date": "Data",
 '4200051': 'Abdon Batista',
 '4200101': 'Abelardo Luz',
 '4200200': 'Agrolândia',
 '4200309': 'Agronômica',
 '4200408': 'Água Doce',
 '4200507': 'Águas de Chapecó',
 '4200556': 'Águas Frias',
 '4200606': 'Águas Mornas',
 '4200705': 'Alfredo Wagner',
 '4200754': 'Alto Bela Vista',
 '4200804': 'Anchieta',
 '4200903': 'Angelina',
 '4201000': 'Anita Garibaldi',
 '4201109': 'Anitápolis',
 '4201208': 'Antônio Carlos',
 '4201257': 'Apiúna',
 '4201273': 'Arabutã',
 '4201307': 'Araquari',
 '4201406': 'Araranguá',
 '4201505': 'Armazém',
 '4201604': 'Arroio Trinta',
 '4201653': 'Arvoredo',
 '4201703': 'Ascurra',
 '4201802': 'Atalanta',
 '4201901': 'Aurora',
 '4201950': 'Balneário Arroio do Silva',
 '4202008': 'Balneário Camboriú',
 '4202057': 'Balneário Barra do Sul',
 '4202073': 'Balneário Gaivota',
 '4202081': 'Bandeirante',
 '4202099': 'Barra Bonita',
 '4202107': 'Barra Velha',
 '4202131': 'Bela Vista do Toldo',
 '4202156': 'Belmonte',
 '4202206': 'Benedito Novo',
 '4202305': 'Biguaçu',
 '4202404': 'Blumenau',
 '4202438': 'Bocaina do Sul',
 '4202453': 'Bombinhas',
 '4202503': 'Bom Jardim da Serra',
 '4202537': 'Bom Jesus',
 '4202578': 'Bom Jesus do Oeste',
 '4202602': 'Bom Retiro',
 '4202701': 'Botuverá',
 '4202800': 'Braço do Norte',
 '4202859': 'Braço do Trombudo',
 '4202875': 'Brunópolis',
 '4202909': 'Brusque',
 '4203006': 'Caçador',
 '4203105': 'Caibi',
 '4203154': 'Calmon',
 '4203204': 'Camboriú',
 '4203253': 'Capão Alto',
 '4203303': 'Campo Alegre',
 '4203402': 'Campo Belo do Sul',
 '4203501': 'Campo Erê',
 '4203600': 'Campos Novos',
 '4203709': 'Canelinha',
 '4203808': 'Canoinhas',
 '4203907': 'Capinzal',
 '4203956': 'Capivari de Baixo',
 '4204004': 'Catanduvas',
 '4204103': 'Caxambu do Sul',
 '4204152': 'Celso Ramos',
 '4204178': 'Cerro Negro',
 '4204194': 'Chapadão do Lageado',
 '4204202': 'Chapecó',
 '4204251': 'Cocal do Sul',
 '4204301': 'Concórdia',
 '4204350': 'Cordilheira Alta',
 '4204400': 'Coronel Freitas',
 '4204459': 'Coronel Martins',
 '4204509': 'Corupá',
 '4204558': 'Correia Pinto',
 '4204608': 'Criciúma',
 '4204707': 'Cunha Porã',
 '4204756': 'Cunhataí',
 '4204806': 'Curitibanos',
 '4204905': 'Descanso',
 '4205001': 'Dionísio Cerqueira',
 '4205100': 'Dona Emma',
 '4205159': 'Doutor Pedrinho',
 '4205175': 'Entre Rios',
 '4205191': 'Ermo',
 '4205209': 'Erval Velho',
 '4205308': 'Faxinal dos Guedes',
 '4205357': 'Flor do Sertão',
 '4205407': 'Florianópolis',
 '4205431': 'Formosa do Sul',
 '4205456': 'Forquilhinha',
 '4205506': 'Fraiburgo',
 '4205555': 'Frei Rogério',
 '4205605': 'Galvão',
 '4205704': 'Garopaba',
 '4205803': 'Garuva',
 '4205902': 'Gaspar',
 '4206009': 'Governador Celso Ramos',
 '4206108': 'Grão-Pará',
 '4206207': 'Gravatal',
 '4206306': 'Guabiruba',
 '4206405': 'Guaraciaba',
 '4206504': 'Guaramirim',
 '4206603': 'Guarujá do Sul',
 '4206652': 'Guatambú',
 '4206702': "Herval d'Oeste",
 '4206751': 'Ibiam',
 '4206801': 'Ibicaré',
 '4206900': 'Ibirama',
 '4207007': 'Içara',
 '4207106': 'Ilhota',
 '4207205': 'Imaruí',
 '4207304': 'Imbituba',
 '4207403': 'Imbuia',
 '4207502': 'Indaial',
 '4207577': 'Iomerê',
 '4207601': 'Ipira',
 '4207650': 'Iporã do Oeste',
 '4207684': 'Ipuaçu',
 '4207700': 'Ipumirim',
 '4207759': 'Iraceminha',
 '4207809': 'Irani',
 '4207858': 'Irati',
 '4207908': 'Irineópolis',
 '4208005': 'Itá',
 '4208104': 'Itaiópolis',
 '4208203': 'Itajaí',
 '4208302': 'Itapema',
 '4208401': 'Itapiranga',
 '4208450': 'Itapoá',
 '4208500': 'Ituporanga',
 '4208609': 'Jaborá',
 '4208708': 'Jacinto Machado',
 '4208807': 'Jaguaruna',
 '4208906': 'Jaraguá do Sul',
 '4208955': 'Jardinópolis',
 '4209003': 'Joaçaba',
 '4209102': 'Joinville',
 '4209151': 'José Boiteux',
 '4209177': 'Jupiá',
 '4209201': 'Lacerdópolis',
 '4209300': 'Lages',
 '4209409': 'Laguna',
 '4209458': 'Lajeado Grande',
 '4209508': 'Laurentino',
 '4209607': 'Lauro Müller',
 '4209706': 'Lebon Régis',
 '4209805': 'Leoberto Leal',
 '4209854': 'Lindóia do Sul',
 '4209904': 'Lontras',
 '4210001': 'Luiz Alves',
 '4210035': 'Luzerna',
 '4210050': 'Macieira',
 '4210100': 'Mafra',
 '4210209': 'Major Gercino',
 '4210308': 'Major Vieira',
 '4210407': 'Maracajá',
 '4210506': 'Maravilha',
 '4210555': 'Marema',
 '4210605': 'Massaranduba',
 '4210704': 'Matos Costa',
 '4210803': 'Meleiro',
 '4210852': 'Mirim Doce',
 '4210902': 'Modelo',
 '4211009': 'Mondaí',
 '4211058': 'Monte Carlo',
 '4211108': 'Monte Castelo',
 '4211207': 'Morro da Fumaça',
 '4211256': 'Morro Grande',
 '4211306': 'Navegantes',
 '4211405': 'Nova Erechim',
 '4211454': 'Nova Itaberaba',
 '4211504': 'Nova Trento',
 '4211603': 'Nova Veneza',
 '4211652': 'Novo Horizonte',
 '4211702': 'Orleans',
 '4211751': 'Otacílio Costa',
 '4211801': 'Ouro',
 '4211850': 'Ouro Verde',
 '4211876': 'Paial',
 '4211892': 'Painel',
 '4211900': 'Palhoça',
 '4212007': 'Palma Sola',
 '4212056': 'Palmeira',
 '4212106': 'Palmitos',
 '4212205': 'Papanduva',
 '4212239': 'Paraíso',
 '4212254': 'Passo de Torres',
 '4212270': 'Passos Maia',
 '4212304': 'Paulo Lopes',
 '4212403': 'Pedras Grandes',
 '4212502': 'Penha',
 '4212601': 'Peritiba',
 '4212650': 'Pescaria Brava',
 '4212700': 'Petrolândia',
 '4212809': 'Balneário Piçarras',
 '4212908': 'Pinhalzinho',
 '4213005': 'Pinheiro Preto',
 '4213104': 'Piratuba',
 '4213153': 'Planalto Alegre',
 '4213203': 'Pomerode',
 '4213302': 'Ponte Alta',
 '4213351': 'Ponte Alta do Norte',
 '4213401': 'Ponte Serrada',
 '4213500': 'Porto Belo',
 '4213609': 'Porto União',
 '4213708': 'Pouso Redondo',
 '4213807': 'Praia Grande',
 '4213906': 'Presidente Castello Branco',
 '4214003': 'Presidente Getúlio',
 '4214102': 'Presidente Nereu',
 '4214151': 'Princesa',
 '4214201': 'Quilombo',
 '4214300': 'Rancho Queimado',
 '4214409': 'Rio das Antas',
 '4214508': 'Rio do Campo',
 '4214607': 'Rio do Oeste',
 '4214706': 'Rio dos Cedros',
 '4214805': 'Rio do Sul',
 '4214904': 'Rio Fortuna',
 '4215000': 'Rio Negrinho',
 '4215059': 'Rio Rufino',
 '4215075': 'Riqueza',
 '4215109': 'Rodeio',
 '4215208': 'Romelândia',
 '4215307': 'Salete',
 '4215356': 'Saltinho',
 '4215406': 'Salto Veloso',
 '4215455': 'Sangão',
 '4215505': 'Santa Cecília',
 '4215554': 'Santa Helena',
 '4215604': 'Santa Rosa de Lima',
 '4215653': 'Santa Rosa do Sul',
 '4215679': 'Santa Terezinha',
 '4215687': 'Santa Terezinha do Progresso',
 '4215695': 'Santiago do Sul',
 '4215703': 'Santo Amaro da Imperatriz',
 '4215752': 'São Bernardino',
 '4215802': 'São Bento do Sul',
 '4215901': 'São Bonifácio',
 '4216008': 'São Carlos',
 '4216057': 'São Cristóvão do Sul',
 '4216107': 'São Domingos',
 '4216206': 'São Francisco do Sul',
 '4216255': 'São João do Oeste',
 '4216305': 'São João Batista',
 '4216354': 'São João do Itaperiú',
 '4216404': 'São João do Sul',
 '4216503': 'São Joaquim',
 '4216602': 'São José',
 '4216701': 'São José do Cedro',
 '4216800': 'São José do Cerrito',
 '4216909': 'São Lourenço do Oeste',
 '4217006': 'São Ludgero',
 '4217105': 'São Martinho',
 '4217154': 'São Miguel da Boa Vista',
 '4217204': 'São Miguel do Oeste',
 '4217253': 'São Pedro de Alcântara',
 '4217303': 'Saudades',
 '4217402': 'Schroeder',
 '4217501': 'Seara',
 '4217550': 'Serra Alta',
 '4217600': 'Siderópolis',
 '4217709': 'Sombrio',
 '4217758': 'Sul Brasil',
 '4217808': 'Taió',
 '4217907': 'Tangará',
 '4217956': 'Tigrinhos',
 '4218004': 'Tijucas',
 '4218103': 'Timbé do Sul',
 '4218202': 'Timbó',
 '4218251': 'Timbó Grande',
 '4218301': 'Três Barras',
 '4218350': 'Treviso',
 '4218400': 'Treze de Maio',
 '4218509': 'Treze Tílias',
 '4218608': 'Trombudo Central',
 '4218707': 'Tubarão',
 '4218756': 'Tunápolis',
 '4218806': 'Turvo',
 '4218855': 'União do Oeste',
 '4218905': 'Urubici',
 '4218954': 'Urupema',
 '4219002': 'Urussanga',
 '4219101': 'Vargeão',
 '4219150': 'Vargem',
 '4219176': 'Vargem Bonita',
 '4219200': 'Vidal Ramos',
 '4219309': 'Videira',
 '4219358': 'Vitor Meireles',
 '4219408': 'Witmarsum',
 '4219507': 'Xanxerê',
 '4219606': 'Xavantina',
 '4219705': 'Xaxim',
 '4219853': 'Zortéa',
 '4220000': 'Balneário Rincão'}

dicionario = {'data_caso': 'Data',
 'data_foco': 'Data',
 'Abdon_Batista': 'Abdon Batista',
 'Abelardo_Luz': 'Abelardo Luz',
 'Agrolandia': 'Agrolândia',
 'Agronomica': 'Agronômica',
 'Agua_Doce': 'Água Doce',
 'Aguas_de_Chapeco': 'Águas de Chapecó',
 'Aguas_Frias': 'Águas Frias',
 'Aguas_Mornas': 'Águas Mornas',
 'Alfredo_Wagner': 'Alfredo Wagner',
 'Alto_Bela_Vista': 'Alto Bela Vista',
 'Anchieta': 'Anchieta',
 'Angelina': 'Angelina',
 'Anita_Garibaldi': 'Anita Garibaldi',
 'Anitapolis': 'Anitápolis',
 'Antonio_Carlos': 'Antônio Carlos',
 'Apiuna': 'Apiúna',
 'Arabuta': 'Arabutã',
 'Araquari': 'Araquari',
 'Ararangua': 'Araranguá',
 'Armazem': 'Armazém',
 'Arroio_Trinta': 'Arroio Trinta',
 'Arvoredo': 'Arvoredo',
 'Ascurra': 'Ascurra',
 'Atalanta': 'Atalanta',
 'Aurora': 'Aurora',
 'Balneario_Arroio_do_Silva': 'Balneário Arroio do Silva',
 'Balneario_Camboriu': 'Balneário Camboriú',
 'Balneario_Barra_do_Sul': 'Balneário Barra do Sul',
 'Balneario_Gaivota': 'Balneário Gaivota',
 'Balneario_Picarras': 'Balneário Piçarras',
 'Balneario_Rincao': 'Balneário Rincão',
 'Bandeirante': 'Bandeirante',
 'Barra_Bonita': 'Barra Bonita',
 'Barra_Velha': 'Barra Velha',
 'Bela_Vista_do_Toldo': 'Bela Vista do Toldo',
 'Belmonte': 'Belmonte',
 'Benedito_Novo': 'Benedito Novo',
 'Biguacu': 'Biguaçu',
 'Blumenau': 'Blumenau',
 'Bocaina_do_Sul': 'Bocaina do Sul',
 'Bombinhas': 'Bombinhas',
 'Bom_Jardim_da_Serra': 'Bom Jardim da Serra',
 'Bom_Jesus': 'Bom Jesus',
 'Bom_Jesus_do_Oeste': 'Bom Jesus do Oeste',
 'Bom_Retiro': 'Bom Retiro',
 'Botuvera': 'Botuverá',
 'Braco_do_Norte': 'Braço do Norte',
 'Braco_do_Trombudo': 'Braço do Trombudo',
 'Brunopolis': 'Brunópolis',
 'Brusque': 'Brusque',
 'Cacador': 'Caçador',
 'Caibi': 'Caibi',
 'Calmon': 'Calmon',
 'Camboriu': 'Camboriú',
 'Capao_Alto': 'Capão Alto',
 'Campo_Alegre': 'Campo Alegre',
 'Campo_Belo_do_Sul': 'Campo Belo do Sul',
 'Campo_Ere': 'Campo Erê',
 'Campos_Novos': 'Campos Novos',
 'Canelinha': 'Canelinha',
 'Canoinhas': 'Canoinhas',
 'Capinzal': 'Capinzal',
 'Capivari_de_Baixo': 'Capivari de Baixo',
 'Catanduvas': 'Catanduvas',
 'Caxambu_do_Sul': 'Caxambu do Sul',
 'Celso_Ramos': 'Celso Ramos',
 'Cerro_Negro': 'Cerro Negro',
 'Chapadao_do_Lageado': 'Chapadão do Lageado',
 'Chapeco': 'Chapecó',
 'Cocal_do_Sul': 'Cocal do Sul',
 'Concordia': 'Concórdia',
 'Cordilheira_Alta': 'Cordilheira Alta',
 'Coronel_Freitas': 'Coronel Freitas',
 'Coronel_Martins': 'Coronel Martins',
 'Corupa': 'Corupá',
 'Correia_Pinto': 'Correia Pinto',
 'Criciuma': 'Criciúma',
 'Cunha_Pora': 'Cunha Porã',
 'Cunhatai': 'Cunhataí',
 'Curitibanos': 'Curitibanos',
 'Descanso': 'Descanso',
 'Dionisio_Cerqueira': 'Dionísio Cerqueira',
 'Dona_Emma': 'Dona Emma',
 'Doutor_Pedrinho': 'Doutor Pedrinho',
 'Entre_Rios': 'Entre Rios',
 'Ermo': 'Ermo',
 'Erval_Velho': 'Erval Velho',
 'Faxinal_dos_Guedes': 'Faxinal dos Guedes',
 'Flor_do_Sertao': 'Flor do Sertão',
 'Florianopolis': 'Florianópolis',
 'Formosa_do_Sul': 'Formosa do Sul',
 'Forquilhinha': 'Forquilhinha',
 'Fraiburgo': 'Fraiburgo',
 'Frei_Rogerio': 'Frei Rogério',
 'Galvao': 'Galvão',
 'Garopaba': 'Garopaba',
 'Garuva': 'Garuva',
 'Gaspar': 'Gaspar',
 'Governador_Celso_Ramos': 'Governador Celso Ramos',
 'Grao_Para': 'Grão-Pará',
 'Gravatal': 'Gravatal',
 'Guabiruba': 'Guabiruba',
 'Guaraciaba': 'Guaraciaba',
 'Guaramirim': 'Guaramirim',
 'Guaruja_do_Sul': 'Guarujá do Sul',
 'Guatambu': 'Guatambú',
 "Herval_d'Oeste": "Herval d'Oeste",
 'Ibiam': 'Ibiam',
 'Ibicare': 'Ibicaré',
 'Ibirama': 'Ibirama',
 'Icara': 'Içara',
 'Ilhota': 'Ilhota',
 'Imarui': 'Imaruí',
 'Imbituba': 'Imbituba',
 'Imbuia': 'Imbuia',
 'Indaial': 'Indaial',
 'Iomere': 'Iomerê',
 'Ipira': 'Ipira',
 'Ipora_do_Oeste': 'Iporã do Oeste',
 'Ipuacu': 'Ipuaçu',
 'Ipumirim': 'Ipumirim',
 'Iraceminha': 'Iraceminha',
 'Irani': 'Irani',
 'Irati': 'Irati',
 'Irineopolis': 'Irineópolis',
 'Ita': 'Itá',
 'Itaiopolis': 'Itaiópolis',
 'Itajai': 'Itajaí',
 'Itapema': 'Itapema',
 'Itapiranga': 'Itapiranga',
 'Itapoa': 'Itapoá',
 'Ituporanga': 'Ituporanga',
 'Jabora': 'Jaborá',
 'Jacinto_Machado': 'Jacinto Machado',
 'Jaguaruna': 'Jaguaruna',
 'Jaragua_do_Sul': 'Jaraguá do Sul',
 'Jardinopolis': 'Jardinópolis',
 'Joacaba': 'Joaçaba',
 'Joinville': 'Joinville',
 'Jose_Boiteux': 'José Boiteux',
 'Jupia': 'Jupiá',
 'Lacerdopolis': 'Lacerdópolis',
 'Lages': 'Lages',
 'Laguna': 'Laguna',
 'Lajeado_Grande': 'Lajeado Grande',
 'Laurentino': 'Laurentino',
 'Lauro_Muller': 'Lauro Müller',
 'Lebon_Regis': 'Lebon Régis',
 'Leoberto_Leal': 'Leoberto Leal',
 'Lindoia_do_Sul': 'Lindóia do Sul',
 'Lontras': 'Lontras',
 'Luiz_Alves': 'Luiz Alves',
 'Luzerna': 'Luzerna',
 'Macieira': 'Macieira',
 'Mafra': 'Mafra',
 'Major_Gercino': 'Major Gercino',
 'Major_Vieira': 'Major Vieira',
 'Maracaja': 'Maracajá',
 'Maravilha': 'Maravilha',
 'Marema': 'Marema',
 'Massaranduba': 'Massaranduba',
 'Matos_Costa': 'Matos Costa',
 'Meleiro': 'Meleiro',
 'Mirim_Doce': 'Mirim Doce',
 'Modelo': 'Modelo',
 'Mondai': 'Mondaí',
 'Monte_Carlo': 'Monte Carlo',
 'Monte_Castelo': 'Monte Castelo',
 'Morro_da_Fumaca': 'Morro da Fumaça',
 'Morro_Grande': 'Morro Grande',
 'Navegantes': 'Navegantes',
 'Nova_Erechim': 'Nova Erechim',
 'Nova_Itaberaba': 'Nova Itaberaba',
 'Nova_Trento': 'Nova Trento',
 'Nova_Veneza': 'Nova Veneza',
 'Novo_Horizonte': 'Novo Horizonte',
 'Orleans': 'Orleans',
 'Otacilio_Costa': 'Otacílio Costa',
 'Ouro': 'Ouro',
 'Ouro_Verde': 'Ouro Verde',
 'Paial': 'Paial',
 'Painel': 'Painel',
 'Palhoca': 'Palhoça',
 'Palma_Sola': 'Palma Sola',
 'Palmeira': 'Palmeira',
 'Palmitos': 'Palmitos',
 'Papanduva': 'Papanduva',
 'Paraiso': 'Paraíso',
 'Passo_de_Torres': 'Passo de Torres',
 'Passos_Maia': 'Passos Maia',
 'Paulo_Lopes': 'Paulo Lopes',
 'Pedras_Grandes': 'Pedras Grandes',
 'Penha': 'Penha',
 'Peritiba': 'Peritiba',
 'Pescaria_Brava': 'Pescaria Brava',
 'Petrolandia': 'Petrolândia',
 'Pinhalzinho': 'Pinhalzinho',
 'Pinheiro_Preto': 'Pinheiro Preto',
 'Piratuba': 'Piratuba',
 'Planalto_Alegre': 'Planalto Alegre',
 'Pomerode': 'Pomerode',
 'Ponte_Alta': 'Ponte Alta',
 'Ponte_Alta_do_Norte': 'Ponte Alta do Norte',
 'Ponte_Serrada': 'Ponte Serrada',
 'Porto_Belo': 'Porto Belo',
 'Porto_Uniao': 'Porto União',
 'Pouso_Redondo': 'Pouso Redondo',
 'Praia_Grande': 'Praia Grande',
 'Presidente_Castello_Branco': 'Presidente Castello Branco',
 'Presidente_Getulio': 'Presidente Getúlio',
 'Presidente_Nereu': 'Presidente Nereu',
 'Princesa': 'Princesa',
 'Quilombo': 'Quilombo',
 'Rancho_Queimado': 'Rancho Queimado',
 'Rio_das_Antas': 'Rio das Antas',
 'Rio_do_Campo': 'Rio do Campo',
 'Rio_do_Oeste': 'Rio do Oeste',
 'Rio_dos_Cedros': 'Rio dos Cedros',
 'Rio_do_Sul': 'Rio do Sul',
 'Rio_Fortuna': 'Rio Fortuna',
 'Rio_Negrinho': 'Rio Negrinho',
 'Rio_Rufino': 'Rio Rufino',
 'Riqueza': 'Riqueza',
 'Rodeio': 'Rodeio',
 'Romelandia': 'Romelândia',
 'Salete': 'Salete',
 'Saltinho': 'Saltinho',
 'Salto_Veloso': 'Salto Veloso',
 'Sangao': 'Sangão',
 'Santa_Cecilia': 'Santa Cecília',
 'Santa_Helena': 'Santa Helena',
 'Santa_Rosa_de_Lima': 'Santa Rosa de Lima',
 'Santa_Rosa_do_Sul': 'Santa Rosa do Sul',
 'Santa_Terezinha': 'Santa Terezinha',
 'Santa_Terezinha_do_Progresso': 'Santa Terezinha do Progresso',
 'Santiago_do_Sul': 'Santiago do Sul',
 'Santo_Amaro_da_Imperatriz': 'Santo Amaro da Imperatriz',
 'Sao_Bernardino': 'São Bernardino',
 'Sao_Bento_do_Sul': 'São Bento do Sul',
 'Sao_Bonifacio': 'São Bonifácio',
 'Sao_Carlos': 'São Carlos',
 'Sao_Cristovao_do_Sul': 'São Cristóvão do Sul',
 'Sao_Domingos': 'São Domingos',
 'Sao_Francisco_do_Sul': 'São Francisco do Sul',
 'Sao_Joao_do_Oeste': 'São João do Oeste',
 'Sao_Joao_Batista': 'São João Batista',
 'Sao_Joao_do_Itaperiu': 'São João do Itaperiú',
 'Sao_Joao_do_Sul': 'São João do Sul',
 'Sao_Joaquim': 'São Joaquim',
 'Sao_Jose': 'São José',
 'Sao_Jose_do_Cedro': 'São José do Cedro',
 'Sao_Jose_do_Cerrito': 'São José do Cerrito',
 'Sao_Lourenco_do_Oeste': 'São Lourenço do Oeste',
 'Sao_Ludgero': 'São Ludgero',
 'Sao_Martinho': 'São Martinho',
 'Sao_Miguel_da_Boa_Vista': 'São Miguel da Boa Vista',
 'Sao_Miguel_do_Oeste': 'São Miguel do Oeste',
 'Sao_Pedro_de_Alcantara': 'São Pedro de Alcântara',
 'Saudades': 'Saudades',
 'Schroeder': 'Schroeder',
 'Seara': 'Seara',
 'Serra_Alta': 'Serra Alta',
 'Sideropolis': 'Siderópolis',
 'Sombrio': 'Sombrio',
 'Sul_Brasil': 'Sul Brasil',
 'Taio': 'Taió',
 'Tangara': 'Tangará',
 'Tigrinhos': 'Tigrinhos',
 'Tijucas': 'Tijucas',
 'Timbe_do_Sul': 'Timbé do Sul',
 'Timbo': 'Timbó',
 'Timbo_Grande': 'Timbó Grande',
 'Tres_Barras': 'Três Barras',
 'Treviso': 'Treviso',
 'Treze_de_Maio': 'Treze de Maio',
 'Treze_Tilias': 'Treze Tílias',
 'Trombudo_Central': 'Trombudo Central',
 'Tubarao': 'Tubarão',
 'Tunapolis': 'Tunápolis',
 'Turvo': 'Turvo',
 'Uniao_do_Oeste': 'União do Oeste',
 'Urubici': 'Urubici',
 'Urupema': 'Urupema',
 'Urussanga': 'Urussanga',
 'Vargeao': 'Vargeão',
 'Vargem': 'Vargem',
 'Vargem_Bonita': 'Vargem Bonita',
 'Vidal_Ramos': 'Vidal Ramos',
 'Videira': 'Videira',
 'Vitor_Meireles': 'Vitor Meireles',
 'Witmarsum': 'Witmarsum',
 'Xanxere': 'Xanxerê',
 'Xavantina': 'Xavantina',
 'Xaxim': 'Xaxim',
 'Zortea': 'Zortéa'}

UPPER = {'Abdon Batista': 'ABDON BATISTA',
  'Abelardo Luz': 'ABELARDO LUZ',
  'Agrolândia': 'AGROLÂNDIA',
  'Agronômica': 'AGRONÔMICA',
  'Água Doce': 'ÁGUA DOCE',
  'Águas de Chapecó': 'ÁGUAS DE CHAPECÓ',
  'Águas Frias': 'ÁGUAS FRIAS',
  'Águas Mornas': 'ÁGUAS MORNAS',
  'Alfredo Wagner': 'ALFREDO WAGNER',
  'Alto Bela Vista': 'ALTO BELA VISTA',
  'Anchieta': 'ANCHIETA',
  'Angelina': 'ANGELINA',
  'Anita Garibaldi': 'ANITA GARIBALDI',
  'Anitápolis': 'ANITÁPOLIS',
  'Antônio Carlos': 'ANTÔNIO CARLOS',
  'Apiúna': 'APIÚNA',
  'Arabutã': 'ARABUTÃ',
  'Araquari': 'ARAQUARI',
  'Araranguá': 'ARARANGUÁ',
  'Armazém': 'ARMAZÉM',
  'Arroio Trinta': 'ARROIO TRINTA',
  'Arvoredo': 'ARVOREDO',
  'Ascurra': 'ASCURRA',
  'Atalanta': 'ATALANTA',
  'Aurora': 'AURORA',
  'Balneário Arroio do Silva': 'BALNEÁRIO ARROIO DO SILVA',
  'Balneário Camboriú': 'BALNEÁRIO CAMBORIÚ',
  'Balneário Barra do Sul': 'BALNEÁRIO BARRA DO SUL',
  'Balneário Gaivota': 'BALNEÁRIO GAIVOTA',
  'Bandeirante': 'BANDEIRANTE',
  'Barra Bonita': 'BARRA BONITA',
  'Barra Velha': 'BARRA VELHA',
  'Bela Vista do Toldo': 'BELA VISTA DO TOLDO',
  'Belmonte': 'BELMONTE',
  'Benedito Novo': 'BENEDITO NOVO',
  'Biguaçu': 'BIGUAÇU',
  'Blumenau': 'BLUMENAU',
  'Bocaina do Sul': 'BOCAINA DO SUL',
  'Bombinhas': 'BOMBINHAS',
  'Bom Jardim da Serra': 'BOM JARDIM DA SERRA',
  'Bom Jesus': 'BOM JESUS',
  'Bom Jesus do Oeste': 'BOM JESUS DO OESTE',
  'Bom Retiro': 'BOM RETIRO',
  'Botuverá': 'BOTUVERÁ',
  'Braço do Norte': 'BRAÇO DO NORTE',
  'Braço do Trombudo': 'BRAÇO DO TROMBUDO',
  'Brunópolis': 'BRUNÓPOLIS',
  'Brusque': 'BRUSQUE',
  'Caçador': 'CAÇADOR',
  'Caibi': 'CAIBI',
  'Calmon': 'CALMON',
  'Camboriú': 'CAMBORIÚ',
  'Capão Alto': 'CAPÃO ALTO',
  'Campo Alegre': 'CAMPO ALEGRE',
  'Campo Belo do Sul': 'CAMPO BELO DO SUL',
  'Campo Erê': 'CAMPO ERÊ',
  'Campos Novos': 'CAMPOS NOVOS',
  'Canelinha': 'CANELINHA',
  'Canoinhas': 'CANOINHAS',
  'Capinzal': 'CAPINZAL',
  'Capivari de Baixo': 'CAPIVARI DE BAIXO',
  'Catanduvas': 'CATANDUVAS',
  'Caxambu do Sul': 'CAXAMBU DO SUL',
  'Celso Ramos': 'CELSO RAMOS',
  'Cerro Negro': 'CERRO NEGRO',
  'Chapadão do Lageado': 'CHAPADÃO DO LAGEADO',
  'Chapecó': 'CHAPECÓ',
  'Cocal do Sul': 'COCAL DO SUL',
  'Concórdia': 'CONCÓRDIA',
  'Cordilheira Alta': 'CORDILHEIRA ALTA',
  'Coronel Freitas': 'CORONEL FREITAS',
  'Coronel Martins': 'CORONEL MARTINS',
  'Corupá': 'CORUPÁ',
  'Correia Pinto': 'CORREIA PINTO',
  'Criciúma': 'CRICIÚMA',
  'Cunha Porã': 'CUNHA PORÃ',
  'Cunhataí': 'CUNHATAÍ',
  'Curitibanos': 'CURITIBANOS',
  'Descanso': 'DESCANSO',
  'Dionísio Cerqueira': 'DIONÍSIO CERQUEIRA',
  'Dona Emma': 'DONA EMMA',
  'Doutor Pedrinho': 'DOUTOR PEDRINHO',
  'Entre Rios': 'ENTRE RIOS',
  'Ermo': 'ERMO',
  'Erval Velho': 'ERVAL VELHO',
  'Faxinal dos Guedes': 'FAXINAL DOS GUEDES',
  'Flor do Sertão': 'FLOR DO SERTÃO',
  'Florianópolis': 'FLORIANÓPOLIS',
  'Formosa do Sul': 'FORMOSA DO SUL',
  'Forquilhinha': 'FORQUILHINHA',
  'Fraiburgo': 'FRAIBURGO',
  'Frei Rogério': 'FREI ROGÉRIO',
  'Galvão': 'GALVÃO',
  'Garopaba': 'GAROPABA',
  'Garuva': 'GARUVA',
  'Gaspar': 'GASPAR',
  'Governador Celso Ramos': 'GOVERNADOR CELSO RAMOS',
  'Grão-Pará': 'GRÃO-PARÁ',
  'Gravatal': 'GRAVATAL',
  'Guabiruba': 'GUABIRUBA',
  'Guaraciaba': 'GUARACIABA',
  'Guaramirim': 'GUARAMIRIM',
  'Guarujá do Sul': 'GUARUJÁ DO SUL',
  'Guatambú': 'GUATAMBÚ',
  "Herval d'Oeste": "HERVAL D'OESTE",
  'Ibiam': 'IBIAM',
  'Ibicaré': 'IBICARÉ',
  'Ibirama': 'IBIRAMA',
  'Içara': 'IÇARA',
  'Ilhota': 'ILHOTA',
  'Imaruí': 'IMARUÍ',
  'Imbituba': 'IMBITUBA',
  'Imbuia': 'IMBUIA',
  'Indaial': 'INDAIAL',
  'Iomerê': 'IOMERÊ',
  'Ipira': 'IPIRA',
  'Iporã do Oeste': 'IPORÃ DO OESTE',
  'Ipuaçu': 'IPUAÇU',
  'Ipumirim': 'IPUMIRIM',
  'Iraceminha': 'IRACEMINHA',
  'Irani': 'IRANI',
  'Irati': 'IRATI',
  'Irineópolis': 'IRINEÓPOLIS',
  'Itá': 'ITÁ',
  'Itaiópolis': 'ITAIÓPOLIS',
  'Itajaí': 'ITAJAÍ',
  'Itapema': 'ITAPEMA',
  'Itapiranga': 'ITAPIRANGA',
  'Itapoá': 'ITAPOÁ',
  'Ituporanga': 'ITUPORANGA',
  'Jaborá': 'JABORÁ',
  'Jacinto Machado': 'JACINTO MACHADO',
  'Jaguaruna': 'JAGUARUNA',
  'Jaraguá do Sul': 'JARAGUÁ DO SUL',
  'Jardinópolis': 'JARDINÓPOLIS',
  'Joaçaba': 'JOAÇABA',
  'Joinville': 'JOINVILLE',
  'José Boiteux': 'JOSÉ BOITEUX',
  'Jupiá': 'JUPIÁ',
  'Lacerdópolis': 'LACERDÓPOLIS',
  'Lages': 'LAGES',
  'Laguna': 'LAGUNA',
  'Lajeado Grande': 'LAJEADO GRANDE',
  'Laurentino': 'LAURENTINO',
  'Lauro Müller': 'LAURO MÜLLER',
  'Lebon Régis': 'LEBON RÉGIS',
  'Leoberto Leal': 'LEOBERTO LEAL',
  'Lindóia do Sul': 'LINDÓIA DO SUL',
  'Lontras': 'LONTRAS',
  'Luiz Alves': 'LUIZ ALVES',
  'Luzerna': 'LUZERNA',
  'Macieira': 'MACIEIRA',
  'Mafra': 'MAFRA',
  'Major Gercino': 'MAJOR GERCINO',
  'Major Vieira': 'MAJOR VIEIRA',
  'Maracajá': 'MARACAJÁ',
  'Maravilha': 'MARAVILHA',
  'Marema': 'MAREMA',
  'Massaranduba': 'MASSARANDUBA',
  'Matos Costa': 'MATOS COSTA',
  'Meleiro': 'MELEIRO',
  'Mirim Doce': 'MIRIM DOCE',
  'Modelo': 'MODELO',
  'Mondaí': 'MONDAÍ',
  'Monte Carlo': 'MONTE CARLO',
  'Monte Castelo': 'MONTE CASTELO',
  'Morro da Fumaça': 'MORRO DA FUMAÇA',
  'Morro Grande': 'MORRO GRANDE',
  'Navegantes': 'NAVEGANTES',
  'Nova Erechim': 'NOVA ERECHIM',
  'Nova Itaberaba': 'NOVA ITABERABA',
  'Nova Trento': 'NOVA TRENTO',
  'Nova Veneza': 'NOVA VENEZA',
  'Novo Horizonte': 'NOVO HORIZONTE',
  'Orleans': 'ORLEANS',
  'Otacílio Costa': 'OTACÍLIO COSTA',
  'Ouro': 'OURO',
  'Ouro Verde': 'OURO VERDE',
  'Paial': 'PAIAL',
  'Painel': 'PAINEL',
  'Palhoça': 'PALHOÇA',
  'Palma Sola': 'PALMA SOLA',
  'Palmeira': 'PALMEIRA',
  'Palmitos': 'PALMITOS',
  'Papanduva': 'PAPANDUVA',
  'Paraíso': 'PARAÍSO',
  'Passo de Torres': 'PASSO DE TORRES',
  'Passos Maia': 'PASSOS MAIA',
  'Paulo Lopes': 'PAULO LOPES',
  'Pedras Grandes': 'PEDRAS GRANDES',
  'Penha': 'PENHA',
  'Peritiba': 'PERITIBA',
  'Pescaria Brava': 'PESCARIA BRAVA',
  'Petrolândia': 'PETROLÂNDIA',
  'Balneário Piçarras': 'BALNEÁRIO PIÇARRAS',
  'Pinhalzinho': 'PINHALZINHO',
  'Pinheiro Preto': 'PINHEIRO PRETO',
  'Piratuba': 'PIRATUBA',
  'Planalto Alegre': 'PLANALTO ALEGRE',
  'Pomerode': 'POMERODE',
  'Ponte Alta': 'PONTE ALTA',
  'Ponte Alta do Norte': 'PONTE ALTA DO NORTE',
  'Ponte Serrada': 'PONTE SERRADA',
  'Porto Belo': 'PORTO BELO',
  'Porto União': 'PORTO UNIÃO',
  'Pouso Redondo': 'POUSO REDONDO',
  'Praia Grande': 'PRAIA GRANDE',
  'Presidente Castello Branco': 'PRESIDENTE CASTELLO BRANCO',
  'Presidente Getúlio': 'PRESIDENTE GETÚLIO',
  'Presidente Nereu': 'PRESIDENTE NEREU',
  'Princesa': 'PRINCESA',
  'Quilombo': 'QUILOMBO',
  'Rancho Queimado': 'RANCHO QUEIMADO',
  'Rio das Antas': 'RIO DAS ANTAS',
  'Rio do Campo': 'RIO DO CAMPO',
  'Rio do Oeste': 'RIO DO OESTE',
  'Rio dos Cedros': 'RIO DOS CEDROS',
  'Rio do Sul': 'RIO DO SUL',
  'Rio Fortuna': 'RIO FORTUNA',
  'Rio Negrinho': 'RIO NEGRINHO',
  'Rio Rufino': 'RIO RUFINO',
  'Riqueza': 'RIQUEZA',
  'Rodeio': 'RODEIO',
  'Romelândia': 'ROMELÂNDIA',
  'Salete': 'SALETE',
  'Saltinho': 'SALTINHO',
  'Salto Veloso': 'SALTO VELOSO',
  'Sangão': 'SANGÃO',
  'Santa Cecília': 'SANTA CECÍLIA',
  'Santa Helena': 'SANTA HELENA',
  'Santa Rosa de Lima': 'SANTA ROSA DE LIMA',
  'Santa Rosa do Sul': 'SANTA ROSA DO SUL',
  'Santa Terezinha': 'SANTA TEREZINHA',
  'Santa Terezinha do Progresso': 'SANTA TEREZINHA DO PROGRESSO',
  'Santiago do Sul': 'SANTIAGO DO SUL',
  'Santo Amaro da Imperatriz': 'SANTO AMARO DA IMPERATRIZ',
  'São Bernardino': 'SÃO BERNARDINO',
  'São Bento do Sul': 'SÃO BENTO DO SUL',
  'São Bonifácio': 'SÃO BONIFÁCIO',
  'São Carlos': 'SÃO CARLOS',
  'São Cristóvão do Sul': 'SÃO CRISTÓVÃO DO SUL',
  'São Domingos': 'SÃO DOMINGOS',
  'São Francisco do Sul': 'SÃO FRANCISCO DO SUL',
  'São João do Oeste': 'SÃO JOÃO DO OESTE',
  'São João Batista': 'SÃO JOÃO BATISTA',
  'São João do Itaperiú': 'SÃO JOÃO DO ITAPERIÚ',
  'São João do Sul': 'SÃO JOÃO DO SUL',
  'São Joaquim': 'SÃO JOAQUIM',
  'São José': 'SÃO JOSÉ',
  'São José do Cedro': 'SÃO JOSÉ DO CEDRO',
  'São José do Cerrito': 'SÃO JOSÉ DO CERRITO',
  'São Lourenço do Oeste': 'SÃO LOURENÇO DO OESTE',
  'São Ludgero': 'SÃO LUDGERO',
  'São Martinho': 'SÃO MARTINHO',
  'São Miguel da Boa Vista': 'SÃO MIGUEL DA BOA VISTA',
  'São Miguel do Oeste': 'SÃO MIGUEL DO OESTE',
  'São Pedro de Alcântara': 'SÃO PEDRO DE ALCÂNTARA',
  'Saudades': 'SAUDADES',
  'Schroeder': 'SCHROEDER',
  'Seara': 'SEARA',
  'Serra Alta': 'SERRA ALTA',
  'Siderópolis': 'SIDERÓPOLIS',
  'Sombrio': 'SOMBRIO',
  'Sul Brasil': 'SUL BRASIL',
  'Taió': 'TAIÓ',
  'Tangará': 'TANGARÁ',
  'Tigrinhos': 'TIGRINHOS',
  'Tijucas': 'TIJUCAS',
  'Timbé do Sul': 'TIMBÉ DO SUL',
  'Timbó': 'TIMBÓ',
  'Timbó Grande': 'TIMBÓ GRANDE',
  'Três Barras': 'TRÊS BARRAS',
  'Treviso': 'TREVISO',
  'Treze de Maio': 'TREZE DE MAIO',
  'Treze Tílias': 'TREZE TÍLIAS',
  'Trombudo Central': 'TROMBUDO CENTRAL',
  'Tubarão': 'TUBARÃO',
  'Tunápolis': 'TUNÁPOLIS',
  'Turvo': 'TURVO',
  'União do Oeste': 'UNIÃO DO OESTE',
  'Urubici': 'URUBICI',
  'Urupema': 'URUPEMA',
  'Urussanga': 'URUSSANGA',
  'Vargeão': 'VARGEÃO',
  'Vargem': 'VARGEM',
  'Vargem Bonita': 'VARGEM BONITA',
  'Vidal Ramos': 'VIDAL RAMOS',
  'Videira': 'VIDEIRA',
  'Vitor Meireles': 'VITOR MEIRELES',
  'Witmarsum': 'WITMARSUM',
  'Xanxerê': 'XANXERÊ',
  'Xavantina': 'XAVANTINA',
  'Xaxim': 'XAXIM',
  'Zortéa': 'ZORTÉA',
  'Balneário Rincão': 'BALNEÁRIO RINCÃO'}

_UPPER = {'ABDON_BATISTA': 'ABDON BATISTA',
  'ABELARDO_LUZ': 'ABELARDO LUZ',
  'AGROLANDIA': 'AGROLÂNDIA',
  'AGRONOMICA': 'AGRONÔMICA',
  'AGUA_DOCE': 'ÁGUA DOCE',
  'AGUAS_DE_CHAPECO': 'ÁGUAS DE CHAPECÓ',
  'AGUAS_FRIAS': 'ÁGUAS FRIAS',
  'AGUAS_MORNAS': 'ÁGUAS MORNAS',
  'ALFREDO_WAGNER': 'ALFREDO WAGNER',
  'ALTO_BELA_VISTA': 'ALTO BELA VISTA',
  'ANCHIETA': 'ANCHIETA',
  'ANGELINA': 'ANGELINA',
  'ANITA_GARIBALDI': 'ANITA GARIBALDI',
  'ANITAPOLIS': 'ANITÁPOLIS',
  'ANTONIO_CARLOS': 'ANTÔNIO CARLOS',
  'APIUNA': 'APIÚNA',
  'ARABUTA': 'ARABUTÃ',
  'ARAQUARI': 'ARAQUARI',
  'ARARANGUA': 'ARARANGUÁ',
  'ARMAZEM': 'ARMAZÉM',
  'ARROIO_TRINTA': 'ARROIO TRINTA',
  'ARVOREDO': 'ARVOREDO',
  'ASCURRA': 'ASCURRA',
  'ATALANTA': 'ATALANTA',
  'AURORA': 'AURORA',
  'BALNEARIO_ARROIO_DO_SILVA': 'BALNEÁRIO ARROIO DO SILVA',
  'BALNEARIO_CAMBORIU': 'BALNEÁRIO CAMBORIÚ',
  'BALNEARIO_BARRA_DO_SUL': 'BALNEÁRIO BARRA DO SUL',
  'BALNEARIO_GAIVOTA': 'BALNEÁRIO GAIVOTA',
  'BANDEIRANTE': 'BANDEIRANTE',
  'BARRA_BONITA': 'BARRA BONITA',
  'BARRA_VELHA': 'BARRA VELHA',
  'BELA_VISTA_DO_TOLDO': 'BELA VISTA DO TOLDO',
  'BELMONTE': 'BELMONTE',
  'BENEDITO_NOVO': 'BENEDITO NOVO',
  'BIGUACU': 'BIGUAÇU',
  'BLUMENAU': 'BLUMENAU',
  'BOCAINA_DO_SUL': 'BOCAINA DO SUL',
  'BOMBINHAS': 'BOMBINHAS',
  'BOM_JARDIM_DA_SERRA': 'BOM JARDIM DA SERRA',
  'BOM_JESUS': 'BOM JESUS',
  'BOM_JESUS_DO_OESTE': 'BOM JESUS DO OESTE',
  'BOM_RETIRO': 'BOM RETIRO',
  'BOTUVERA': 'BOTUVERÁ',
  'BRACO_DO_NORTE': 'BRAÇO DO NORTE',
  'BRACO_DO_TROMBUDO': 'BRAÇO DO TROMBUDO',
  'BRUNOPOLIS': 'BRUNÓPOLIS',
  'BRUSQUE': 'BRUSQUE',
  'CACADOR': 'CAÇADOR',
  'CAIBI': 'CAIBI',
  'CALMON': 'CALMON',
  'CAMBORIU': 'CAMBORIÚ',
  'CAPAO_ALTO': 'CAPÃO ALTO',
  'CAMPO_ALEGRE': 'CAMPO ALEGRE',
  'CAMPO_BELO_DO_SUL': 'CAMPO BELO DO SUL',
  'CAMPO_ERE': 'CAMPO ERÊ',
  'CAMPOS_NOVOS': 'CAMPOS NOVOS',
  'CANELINHA': 'CANELINHA',
  'CANOINHAS': 'CANOINHAS',
  'CAPINZAL': 'CAPINZAL',
  'CAPIVARI_DE_BAIXO': 'CAPIVARI DE BAIXO',
  'CATANDUVAS': 'CATANDUVAS',
  'CAXAMBU_DO_SUL': 'CAXAMBU DO SUL',
  'CELSO_RAMOS': 'CELSO RAMOS',
  'CERRO_NEGRO': 'CERRO NEGRO',
  'CHAPADAO_DO_LAGEADO': 'CHAPADÃO DO LAGEADO',
  'CHAPECO': 'CHAPECÓ',
  'COCAL_DO_SUL': 'COCAL DO SUL',
  'CONCORDIA': 'CONCÓRDIA',
  'CORDILHEIRA_ALTA': 'CORDILHEIRA ALTA',
  'CORONEL_FREITAS': 'CORONEL FREITAS',
  'CORONEL_MARTINS': 'CORONEL MARTINS',
  'CORUPA': 'CORUPÁ',
  'CORREIA_PINTO': 'CORREIA PINTO',
  'CRICIUMA': 'CRICIÚMA',
  'CUNHA_PORA': 'CUNHA PORÃ',
  'CUNHATAO': 'CUNHATAÍ',
  'CURITIBANOS': 'CURITIBANOS',
  'DESCANSO': 'DESCANSO',
  'DIONOSIO_CERQUEIRA': 'DIONÍSIO CERQUEIRA',
  'DONA_EMMA': 'DONA EMMA',
  'DOUTOR_PEDRINHO': 'DOUTOR PEDRINHO',
  'ENTRE_RIOS': 'ENTRE RIOS',
  'ERMO': 'ERMO',
  'ERVAL_VELHO': 'ERVAL VELHO',
  'FAXINAL_DOS_GUEDES': 'FAXINAL DOS GUEDES',
  'FLOR_DO_SERTAO': 'FLOR DO SERTÃO',
  'FLORIANOPOLIS': 'FLORIANÓPOLIS',
  'FORMOSA_DO_SUL': 'FORMOSA DO SUL',
  'FORQUILHINHA': 'FORQUILHINHA',
  'FRAIBURGO': 'FRAIBURGO',
  'FREI_ROGERIO': 'FREI ROGÉRIO',
  'GALVAO': 'GALVÃO',
  'GAROPABA': 'GAROPABA',
  'GARUVA': 'GARUVA',
  'GASPAR': 'GASPAR',
  'GOVERNADOR_CELSO_RAMOS': 'GOVERNADOR CELSO RAMOS',
  'GRAO_PARA': 'GRÃO-PARÁ',
  'GRAVATAL': 'GRAVATAL',
  'GUABIRUBA': 'GUABIRUBA',
  'GUARACIABA': 'GUARACIABA',
  'GUARAMIRIM': 'GUARAMIRIM',
  'GUARUJA_DO_SUL': 'GUARUJÁ DO SUL',
  'GUATAMBU': 'GUATAMBÚ',
  'HERVAL_D_OESTE': "HERVAL D'OESTE",
  'IBIAM': 'IBIAM',
  'IBICARE': 'IBICARÉ',
  'IBIRAMA': 'IBIRAMA',
  'ICARA': 'IÇARA',
  'ILHOTA': 'ILHOTA',
  'IMARUO': 'IMARUÍ',
  'IMBITUBA': 'IMBITUBA',
  'IMBUIA': 'IMBUIA',
  'INDAIAL': 'INDAIAL',
  'IOMERE': 'IOMERÊ',
  'IPIRA': 'IPIRA',
  'IPORA_DO_OESTE': 'IPORÃ DO OESTE',
  'IPUACU': 'IPUAÇU',
  'IPUMIRIM': 'IPUMIRIM',
  'IRACEMINHA': 'IRACEMINHA',
  'IRANI': 'IRANI',
  'IRATI': 'IRATI',
  'IRINEOPOLIS': 'IRINEÓPOLIS',
  'ITA': 'ITÁ',
  'ITAIOPOLIS': 'ITAIÓPOLIS',
  'ITAJAO': 'ITAJAÍ',
  'ITAPEMA': 'ITAPEMA',
  'ITAPIRANGA': 'ITAPIRANGA',
  'ITAPOA': 'ITAPOÁ',
  'ITUPORANGA': 'ITUPORANGA',
  'JABORA': 'JABORÁ',
  'JACINTO_MACHADO': 'JACINTO MACHADO',
  'JAGUARUNA': 'JAGUARUNA',
  'JARAGUA_DO_SUL': 'JARAGUÁ DO SUL',
  'JARDINOPOLIS': 'JARDINÓPOLIS',
  'JOACABA': 'JOAÇABA',
  'JOINVILLE': 'JOINVILLE',
  'JOSE_BOITEUX': 'JOSÉ BOITEUX',
  'JUPIA': 'JUPIÁ',
  'LACERDOPOLIS': 'LACERDÓPOLIS',
  'LAGES': 'LAGES',
  'LAGUNA': 'LAGUNA',
  'LAJEADO_GRANDE': 'LAJEADO GRANDE',
  'LAURENTINO': 'LAURENTINO',
  'LAURO_MULLER': 'LAURO MÜLLER',
  'LEBON_REGIS': 'LEBON RÉGIS',
  'LEOBERTO_LEAL': 'LEOBERTO LEAL',
  'LINDOIA_DO_SUL': 'LINDÓIA DO SUL',
  'LONTRAS': 'LONTRAS',
  'LUIZ_ALVES': 'LUIZ ALVES',
  'LUZERNA': 'LUZERNA',
  'MACIEIRA': 'MACIEIRA',
  'MAFRA': 'MAFRA',
  'MAJOR_GERCINO': 'MAJOR GERCINO',
  'MAJOR_VIEIRA': 'MAJOR VIEIRA',
  'MARACAJA': 'MARACAJÁ',
  'MARAVILHA': 'MARAVILHA',
  'MAREMA': 'MAREMA',
  'MASSARANDUBA': 'MASSARANDUBA',
  'MATOS_COSTA': 'MATOS COSTA',
  'MELEIRO': 'MELEIRO',
  'MIRIM_DOCE': 'MIRIM DOCE',
  'MODELO': 'MODELO',
  'MONDAO': 'MONDAÍ',
  'MONTE_CARLO': 'MONTE CARLO',
  'MONTE_CASTELO': 'MONTE CASTELO',
  'MORRO_DA_FUMACA': 'MORRO DA FUMAÇA',
  'MORRO_GRANDE': 'MORRO GRANDE',
  'NAVEGANTES': 'NAVEGANTES',
  'NOVA_ERECHIM': 'NOVA ERECHIM',
  'NOVA_ITABERABA': 'NOVA ITABERABA',
  'NOVA_TRENTO': 'NOVA TRENTO',
  'NOVA_VENEZA': 'NOVA VENEZA',
  'NOVO_HORIZONTE': 'NOVO HORIZONTE',
  'ORLEANS': 'ORLEANS',
  'OTACOLIO_COSTA': 'OTACÍLIO COSTA',
  'OURO': 'OURO',
  'OURO_VERDE': 'OURO VERDE',
  'PAIAL': 'PAIAL',
  'PAINEL': 'PAINEL',
  'PALHOCA': 'PALHOÇA',
  'PALMA_SOLA': 'PALMA SOLA',
  'PALMEIRA': 'PALMEIRA',
  'PALMITOS': 'PALMITOS',
  'PAPANDUVA': 'PAPANDUVA',
  'PARAOSO': 'PARAÍSO',
  'PASSO_DE_TORRES': 'PASSO DE TORRES',
  'PASSOS_MAIA': 'PASSOS MAIA',
  'PAULO_LOPES': 'PAULO LOPES',
  'PEDRAS_GRANDES': 'PEDRAS GRANDES',
  'PENHA': 'PENHA',
  'PERITIBA': 'PERITIBA',
  'PESCARIA_BRAVA': 'PESCARIA BRAVA',
  'PETROLANDIA': 'PETROLÂNDIA',
  'BALNEARIO_PICARRAS': 'BALNEÁRIO PIÇARRAS',
  'PINHALZINHO': 'PINHALZINHO',
  'PINHEIRO_PRETO': 'PINHEIRO PRETO',
  'PIRATUBA': 'PIRATUBA',
  'PLANALTO_ALEGRE': 'PLANALTO ALEGRE',
  'POMERODE': 'POMERODE',
  'PONTE_ALTA': 'PONTE ALTA',
  'PONTE_ALTA_DO_NORTE': 'PONTE ALTA DO NORTE',
  'PONTE_SERRADA': 'PONTE SERRADA',
  'PORTO_BELO': 'PORTO BELO',
  'PORTO_UNIAO': 'PORTO UNIÃO',
  'POUSO_REDONDO': 'POUSO REDONDO',
  'PRAIA_GRANDE': 'PRAIA GRANDE',
  'PRESIDENTE_CASTELLO_BRANCO': 'PRESIDENTE CASTELLO BRANCO',
  'PRESIDENTE_GETULIO': 'PRESIDENTE GETÚLIO',
  'PRESIDENTE_NEREU': 'PRESIDENTE NEREU',
  'PRINCESA': 'PRINCESA',
  'QUILOMBO': 'QUILOMBO',
  'RANCHO_QUEIMADO': 'RANCHO QUEIMADO',
  'RIO_DAS_ANTAS': 'RIO DAS ANTAS',
  'RIO_DO_CAMPO': 'RIO DO CAMPO',
  'RIO_DO_OESTE': 'RIO DO OESTE',
  'RIO_DOS_CEDROS': 'RIO DOS CEDROS',
  'RIO_DO_SUL': 'RIO DO SUL',
  'RIO_FORTUNA': 'RIO FORTUNA',
  'RIO_NEGRINHO': 'RIO NEGRINHO',
  'RIO_RUFINO': 'RIO RUFINO',
  'RIQUEZA': 'RIQUEZA',
  'RODEIO': 'RODEIO',
  'ROMELANDIA': 'ROMELÂNDIA',
  'SALETE': 'SALETE',
  'SALTINHO': 'SALTINHO',
  'SALTO_VELOSO': 'SALTO VELOSO',
  'SANGAO': 'SANGÃO',
  'SANTA_CECOLIA': 'SANTA CECÍLIA',
  'SANTA_HELENA': 'SANTA HELENA',
  'SANTA_ROSA_DE_LIMA': 'SANTA ROSA DE LIMA',
  'SANTA_ROSA_DO_SUL': 'SANTA ROSA DO SUL',
  'SANTA_TEREZINHA': 'SANTA TEREZINHA',
  'SANTA_TEREZINHA_DO_PROGRESSO': 'SANTA TEREZINHA DO PROGRESSO',
  'SANTIAGO_DO_SUL': 'SANTIAGO DO SUL',
  'SANTO_AMARO_DA_IMPERATRIZ': 'SANTO AMARO DA IMPERATRIZ',
  'SAO_BERNARDINO': 'SÃO BERNARDINO',
  'SAO_BENTO_DO_SUL': 'SÃO BENTO DO SUL',
  'SAO_BONIFACIO': 'SÃO BONIFÁCIO',
  'SAO_CARLOS': 'SÃO CARLOS',
  'SAO_CRISTOVAO_DO_SUL': 'SÃO CRISTÓVÃO DO SUL',
  'SAO_DOMINGOS': 'SÃO DOMINGOS',
  'SAO_FRANCISCO_DO_SUL': 'SÃO FRANCISCO DO SUL',
  'SAO_JOAO_DO_OESTE': 'SÃO JOÃO DO OESTE',
  'SAO_JOAO_BATISTA': 'SÃO JOÃO BATISTA',
  'SAO_JOAO_DO_ITAPERIU': 'SÃO JOÃO DO ITAPERIÚ',
  'SAO_JOAO_DO_SUL': 'SÃO JOÃO DO SUL',
  'SAO_JOAQUIM': 'SÃO JOAQUIM',
  'SAO_JOSE': 'SÃO JOSÉ',
  'SAO_JOSE_DO_CEDRO': 'SÃO JOSÉ DO CEDRO',
  'SAO_JOSE_DO_CERRITO': 'SÃO JOSÉ DO CERRITO',
  'SAO_LOURENCO_DO_OESTE': 'SÃO LOURENÇO DO OESTE',
  'SAO_LUDGERO': 'SÃO LUDGERO',
  'SAO_MARTINHO': 'SÃO MARTINHO',
  'SAO_MIGUEL_DA_BOA_VISTA': 'SÃO MIGUEL DA BOA VISTA',
  'SAO_MIGUEL_DO_OESTE': 'SÃO MIGUEL DO OESTE',
  'SAO_PEDRO_DE_ALCANTARA': 'SÃO PEDRO DE ALCÂNTARA',
  'SAUDADES': 'SAUDADES',
  'SCHROEDER': 'SCHROEDER',
  'SEARA': 'SEARA',
  'SERRA_ALTA': 'SERRA ALTA',
  'SIDEROPOLIS': 'SIDERÓPOLIS',
  'SOMBRIO': 'SOMBRIO',
  'SUL_BRASIL': 'SUL BRASIL',
  'TAIO': 'TAIÓ',
  'TANGARA': 'TANGARÁ',
  'TIGRINHOS': 'TIGRINHOS',
  'TIJUCAS': 'TIJUCAS',
  'TIMBE_DO_SUL': 'TIMBÉ DO SUL',
  'TIMBO': 'TIMBÓ',
  'TIMBO_GRANDE': 'TIMBÓ GRANDE',
  'TRES_BARRAS': 'TRÊS BARRAS',
  'TREVISO': 'TREVISO',
  'TREZE_DE_MAIO': 'TREZE DE MAIO',
  'TREZE_TOLIAS': 'TREZE TÍLIAS',
  'TROMBUDO_CENTRAL': 'TROMBUDO CENTRAL',
  'TUBARAO': 'TUBARÃO',
  'TUNAPOLIS': 'TUNÁPOLIS',
  'TURVO': 'TURVO',
  'UNIAO_DO_OESTE': 'UNIÃO DO OESTE',
  'URUBICI': 'URUBICI',
  'URUPEMA': 'URUPEMA',
  'URUSSANGA': 'URUSSANGA',
  'VARGEAO': 'VARGEÃO',
  'VARGEM': 'VARGEM',
  'VARGEM_BONITA': 'VARGEM BONITA',
  'VIDAL_RAMOS': 'VIDAL RAMOS',
  'VIDEIRA': 'VIDEIRA',
  'VITOR_MEIRELES': 'VITOR MEIRELES',
  'WITMARSUM': 'WITMARSUM',
  'XANXERE': 'XANXERÊ',
  'XAVANTINA': 'XAVANTINA',
  'XAXIM': 'XAXIM',
  'ZORTEA': 'ZORTÉA',
  'BALNEARIO_RINCAO': 'BALNEÁRIO RINCÃO'}


### Pré-Processamento
### Transformando em datetime64[ns] e Renomeando colunas
focos["data"] = focos["data_foco"]
focos["data_foco"] = pd.to_datetime(focos["data_foco"], infer_datetime_format = True)
focos = focos.sort_values(by = ["data_foco"])
focos = focos.rename(columns = dicionario)

casos["Semana"] = casos["data_caso"] # Porque estes dados já estão agrupados em Semanas Epidemiológicas
casos["data_caso"] = pd.to_datetime(casos["data_caso"], infer_datetime_format = True)
casos = casos.sort_values(by = ["data_caso"])
casos = casos.rename(columns = dicionario)
casos.drop(columns = "Data", inplace = True)
casos = casos.rename(columns = UPPER)
"""
for columns in casos.columns:
    casos[columns] = casos[columns].astype(np.float32)#.str.upper()
"""
merge["data"] = merge["date"]
merge["data"] = pd.to_datetime(merge["date"], infer_datetime_format = True)
merge = merge.sort_values(by = ["date"])
merge = merge.rename(columns = lista)

tmin["data"] = tmin["date"]
tmin["data"] = pd.to_datetime(tmin["date"], infer_datetime_format = True)
tmin = tmin.sort_values(by = ["date"])
tmin = tmin.rename(columns = lista)

tmed["data"] = tmed["date"]
tmed["data"] = pd.to_datetime(tmed["date"], infer_datetime_format = True)
tmed = tmed.sort_values(by = ["date"])
tmed = tmed.rename(columns = lista)

tmax["data"] = tmax["date"]
tmax["data"] = pd.to_datetime(tmax["date"], infer_datetime_format = True)
tmax = tmax.sort_values(by = ["date"])
tmax = tmax.rename(columns = lista)

### Padronizando Colunas (.upper())
### Agrupando Dados em Semanas Epidemiológicas E Retirando 1ª Linha das Temperaturas (final_1999)
merge_se = merge.copy()
merge_se["Semana"] = merge_se["data"].dt.to_period("W-SAT").dt.to_timestamp()
merge_se = merge_se.groupby(["Semana"]).sum(numeric_only = True)
merge_se.reset_index(inplace = True)
merge_se = merge_se.rename(columns = UPPER)

tmin_se = tmin.copy()
tmin_se["Semana"] = tmin_se["data"].dt.to_period("W-SAT").dt.to_timestamp()
tmin_se = tmin_se.groupby(["Semana"]).mean(numeric_only = True)
tmin_se.reset_index(inplace = True)
tmin_se.drop([0], inplace = True)
tmin_se = tmin_se.rename(columns = UPPER)

tmed_se = tmed.copy()
tmed_se["Semana"] = tmed_se["data"].dt.to_period("W-SAT").dt.to_timestamp()
tmed_se = tmed_se.groupby(["Semana"]).mean(numeric_only = True)
tmed_se.reset_index(inplace = True)
tmed_se.drop([0], inplace = True)
tmed_se = tmed_se.rename(columns = UPPER)

tmax_se = tmax.copy()
tmax_se["Semana"] = tmax_se["data"].dt.to_period("W-SAT").dt.to_timestamp()
tmax_se = tmax_se.groupby(["Semana"]).mean(numeric_only = True)
tmax_se.reset_index(inplace = True)
tmax_se.drop([0], inplace = True)
tmax_se = tmax_se.rename(columns = UPPER)

### Salvando Variáveis em Novos Arquivos
#focos.to_csv(f"{caminho_dados}focos.csv", index = False) ||| ARQUIVO focos_pivot.csv está atualizado!
casos.to_csv(f"{caminho_dados}casos_se.csv", index = False)
merge.to_csv(f"{caminho_dados}merge_novo.csv", index = False)
tmin.to_csv(f"{caminho_dados}tmin.csv", index = False)
tmed.to_csv(f"{caminho_dados}tmed.csv", index = False)
tmax.to_csv(f"{caminho_dados}tmax.csv", index = False)
merge_se.to_csv(f"{caminho_dados}merge_se.csv", index = False)
tmin_se.to_csv(f"{caminho_dados}tmin_se.csv", index = False)
tmed_se.to_csv(f"{caminho_dados}tmed_se.csv", index = False)
tmax_se.to_csv(f"{caminho_dados}tmax_se.csv", index = False)

### Exibindo Dados e Informações
print("\n \n FOCOS DE _Aedes aegypti_ >> OK \n")
print(focos.info())
print("~"*80)
print(focos.dtypes)
print("~"*80)
print(focos)
print("="*80)

print("\n \n CASOS DE DENGUE >> OK \n")
print(casos.info())
print("~"*80)
print(casos.dtypes)
print("~"*80)
print(casos)
print("="*80)

print("\n \n PRECIPITAÇÃO >> OK \n")
print(merge.info())
print("~"*80)
print(merge.dtypes)
print("~"*80)
print(merge.head())
print("="*80)

print("\n \n TEMPERATURA MÍNIMA >> OK \n")
print(tmin.info())
print("~"*80)
print(tmin.dtypes)
print("~"*80)
print(tmin.head())
print("="*80)

print("\n \n TEMPERATURA MÉDIA >> OK \n")
print(tmed.info())
print("~"*80)
print(tmed.dtypes)
print("~"*80)
print(tmed.head())
print("="*80)

print("\n \n TEMPERATURA MÁXIMA >> OK \n")
print(tmax.info())
print("~"*80)
print(tmax.dtypes)
print("~"*80)
print(tmax.head())
print("="*80)

print("\n \n PRECIPITAÇÃO / SEMANA EPIDEMIOLÓGICA >> OK \n")
print(merge_se.info())
print("~"*80)
print(merge_se.dtypes)
print("~"*80)
print(merge_se)
print("="*80)

print("\n \n TEMPERATURA MÍNIMA / SEMANA EPIDEMIOLÓGICA >> OK \n")
print(tmin_se.info())
print("~"*80)
print(tmin_se.dtypes)
print("~"*80)
print(tmin_se)
print("="*80)

print("\n \n TEMPERATURA MÉDIA / SEMANA EPIDEMIOLÓGICA >> OK \n")
print(tmed_se.info())
print("~"*80)
print(tmed_se.dtypes)
print("~"*80)
print(tmed_se)
print("="*80)

print("\n \n TEMPERATURA MÁXIMA / SEMANA EPIDEMIOLÓGICA >> OK \n")
print(tmax_se.info())
print("~"*80)
print(tmax_se.dtypes)
print("~"*80)
print(tmax_se)
print("="*80)
